version: '3'

services:
  db:
    container_name: my-postgres
    image: postgres:10.5
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - postgres-data:/var/lib/postgressql/data
    environment:
      - POSTGRES_PASSWORD=password
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5      

volumes:
  postgres-data: {}
